### ISSUE TITLE
[BUG]: reconfigureParams.reInitEncodeParams.frameRateNum = m_codec.maxFramerate appears to have no impact on received framerates

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/com.unity.webrtc#704]
### Package version

2.4.0-exp.7

### Environment

```markdown
* OS: Windows 11
* Unity version: 2021.2.15f1
```

### Steps To Reproduce

1. Set m_codec.maxFramerate to 60 in SetRates.
2. Observe that on a 144hz display device like mine, chrome://webrtc-internals still reports receiving 100+ frames per second.

### Current Behavior

Greater than 100 fps when I want to cap it at 60.

### Expected Behavior

Capping at 60.

### Anything else?

Setting the framerate in the encoding on RTP Sender has no impact on the hardware encoder. Software codec is too slow to validate the impact.

**Comment by karasusan** [comment]
We have not investigated the issue enough, but I guess, first we should fix the issue below.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/550

**Comment by doctorpangloss** [comment]
Setting `Application.targetFramerate = 60` in the editor also does not resolve the issue, but that may be editor specific.

**Comment by karasusan** [comment]
@doctorpangloss
Is this issue reproduced by the runtime?

**Comment by karasusan** [comment]
memo: WRS-301

**Comment by doctorpangloss** [comment]
> @doctorpangloss
> Is this issue reproduced by the runtime?

Not completely sure yet... I will update you. Lots of things interact with the frame rate.

**Comment by karasusan** [comment]
@doctorpangloss
Hi, we fixed the encoding framerate related to your issue. #728
We want to check the issue using the latest code. Could you tell me how to reproduce your issue?

**Comment by karasusan** [comment]
@doctorpangloss
May I change the status of the issue to done?

**Comment by karasusan** [comment]
@doctorpangloss
Any update?

**Comment by doctorpangloss** [comment]
This is resolved!
