### ISSUE TITLE
[BUG]: windows - video resize callback not called

### ISSUE THREAD

**Issue by mgodfreymodest** [Unity-Technologies/com.unity.webrtc#731]
### Package version

2.4.0-exp.7

### Environment

```markdown
* OS:Windows 10
* Unity version:2019.4
```

### Steps To Reproduce

1. establish a stream between android and Windows, including video
2. call `ReplaceTrack` on the video track on Android, including a size change
3. observe on Windows that `UnityVideoRenderer.OnVideoFrameResize` does not get called on Windows

### Current Behavior

`OnVideoFrameResize` doesn't get called, but only on Windows. `ReplaceTrack` with a new video track of the same size continues to stream. Changing the video stream on Windows, the `OnVideoFrameResize` call happens on Android. 

### Expected Behavior

Windows should also receive the callback from the c++ side.

### Anything else?

This is a new issue, not found in 2.4.0-exp6.

**Comment by mgodfreymodest** [comment]
More details: 
A texture of size 720x405 does not trigger the callback.
A texture of size 720x400 does trigger the callback.

Do the dimensions need to be a multiple of some number?

**Comment by karasusan** [comment]
@mgodfreymodest
Thank you for details. That is weird...
Do you know what codec you are using?

**Comment by mgodfreymodest** [comment]
I'm not sure exactly how to get the codec information, but the documentation suggests looking at the RTCRtpSender.

On Android I get the following mime types out of the sender codecs field:
video/VP8, video/H264, video/VP9 and video/rtx

On Windows I get the following mime types out of the sender codecs field:
video/VP8, video/H264, video/VP9 and video/rtx

Is this useful information?

**Comment by karasusan** [comment]
VP8 codec on windows. it works.

https://user-images.githubusercontent.com/1132081/171544759-347e1b47-e312-42f1-8040-0482451ff035.mp4

**Comment by mgodfreymodest** [comment]
Using exp7 with the develop's sample scenes, my h264 codecs do a mix of changing the resolution from 720x405 on the send side to 720x406 on the received video, and crashing unity when you replace tracks to a differently-sized video. 

There are several h264 options, in the following format, all behaving this way:
![Screenshot 2022-06-02 103506](https://user-images.githubusercontent.com/72453499/171641717-e0dd6cf3-258e-4a81-a6f4-c085c347d3c9.png)

**Comment by karasusan** [comment]
@mgodfreymodest
Sure, I think the crash is fixed by this PR #737.
Could you test the develop branch?

**Comment by mgodfreymodest** [comment]
I installed the plugin dll's from the develop branch. The sizing issue persists in my app. 

When testing with the ReplaceTrack sample, still getting crashes when replacing from 720x400 to 720x405 using the h264 codecs.

**Comment by karasusan** [comment]
@mgodfreymodest
Ah, I haven't uploaded the latest plugin.
I am checking

**Comment by karasusan** [comment]
@mgodfreymodest
Updated. Please try it again.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/742

**Comment by mgodfreymodest** [comment]
Using the latest plugin version on the sample code, the crash is resolved for h264.

Trying the latest plugin in my app, only even-numbered sizes stream, still.

**Comment by karasusan** [comment]
@mgodfreymodest
Sure, this is a issue that the odd numbered size is resized unintendedly.
